### ISSUE TITLE
debug doesn't really work

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/hapi-view-context#8]
if you manually add view context like the readme says, and debug context, it fires and returns before the other ext is fired.

@dawnerd

**Comment by dawnerd** [comment]
Hmm, I'd have to look at the hapi docs to see what we can do about multiple hooks.

**Comment by jgallen23** [comment]
maybe the plugin itself exposes a hook?  so `server.plugins['hapi-view-data'].onContext((request, context) => { });`

**Comment by dawnerd** [comment]
That'd work but it could be an issue with other plugins

**Comment by jgallen23** [comment]
you mean plugins trying to use this plugin?

**Comment by dawnerd** [comment]
Plugins that also attach to onPreResponse. Hapi is just running the first attached event in the stack

**Comment by jgallen23** [comment]
true.  is there an event after onPreResponse?

**Comment by jgallen23** [comment]
refactored and outputted to console
